[project]
name = "ltfa"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "appdirs",
    "bokeh",
    "matplotlib",
    "pandas",
    "python-dateutil",
    "pyyaml",
    "simplejson",
]

[dependency-groups]
dev = [
    "mypy",
    "pytest",
    "testfixtures",
    "types-appdirs",
    "types-python-dateutil",
    "types-pyyaml",
    "types-simplejson",
]

[tool.uv]
package = false
