version: 2.1

orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.2.0
  shellcheck: circleci/shellcheck@3.1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.13.5
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pipenv sync -v --categories "packages dev-packages test"
      - run:
          name: Verify Pipfile.lock
          command: pipenv verify
      - run:
          name: Run tests
          command: pipenv run pytest

      - python/install-packages:
          args: github-pages-publish~=0.1
          pkg-manager: pip
      - run:
          name: Build demo
          command: |
            mkdir /tmp/demo
            ./ltfa.py --config=demo/demo.conf -o /tmp/demo
            github-pages-publish -h
            git config user.email "circleci@example.com"
            git config user.name "CircleCI"
            github-pages-publish --verbose -c dnnr.github.io . /tmp/demo
            #git push origin gh-pages:gh-pages
            git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/dnnr/ltfa.git gh-pages:gh-pages


  check-single-commit:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: git remote -v
      - run:
          command: git branch -a
      - run:
          name: Check maximum of one commit after origin/HEAD
          command: |
            git rev-list HEAD ^origin/HEAD
            test $(git rev-list HEAD ^origin/HEAD | wc -l) -le 1

workflows:
  ci:
    jobs:
      - build-and-test
      - check-single-commit
      - shellcheck/check
