version: 2.1

orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.2.0
  shellcheck: circleci/shellcheck@3.1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pipenv sync -v --categories "packages dev-packages test"
      - run:
          name: Verify Pipfile.lock
          command: pipenv verify
      - run:
          name: Run tests
          command: pipenv run pytest
      - run:
          name: Run mypy
          command: pipenv run mypy --ignore-missing-imports ltfa

  check-single-commit:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: git remote -v
      - run:
          command: git branch -a
      - run:
          name: Check maximum of one commit after origin/HEAD
          command: |
            git rev-list HEAD ^origin/HEAD
            test $(git rev-list HEAD ^origin/HEAD | wc -l) -le 1

workflows:
  ci:
    jobs:
      - build-and-test
      - check-single-commit
      - docker/hadolint:
          dockerfiles: Dockerfile
      - shellcheck/check
